export const BOARDS = [
  { text: "8 Bit", value: "8_bit" },
  { text: "Bases", value: "bases" },
  { text: "Blue", value: "blue" },
  { text: "Brown", value: "brown" },
  { text: "Burled Wood", value: "burled_wood" },
  { text: "Checkers", value: "checkers" },
  { text: "Dark Wood", value: "dark_wood" },
  { text: "Dash", value: "dash" },
  { text: "Glass", value: "glass" },
  { text: "Graffiti", value: "graffiti" },
  { text: "Green", value: "green", default: true },
  { text: "Icy Sea", value: "icy_sea" },
  { text: "Light", value: "light" },
  { text: "Lolz", value: "lolz" },
  { text: "Marble", value: "marble" },
  { text: "Metal", value: "metal" },
  { text: "Neon", value: "neon" },
  { text: "Newspaper", value: "newspaper" },
  { text: "Orange", value: "orange" },
  { text: "Parchment", value: "parchment" },
  { text: "Purple", value: "purple" },
  { text: "Red", value: "red" },
  { text: "Sand", value: "sand" },
  { text: "Sky", value: "sky" },
  { text: "Stone", value: "stone" },
  { text: "Tan", value: "tan" },
  { text: "Tournament", value: "tournament" },
  { text: "Translucent", value: "translucent" },
  { text: "Walnut", value: "walnut" },
];
