export const PIECES = [
  { text: "8 Bit", value: "8_bit" },
  { text: "Alpha", value: "alpha" },
  { text: "Bases", value: "bases", default: true },
  { text: "Book", value: "book" },
  { text: "Bubblegum", value: "bubblegum" },
  { text: "Cases", value: "cases" },
  { text: "Classic", value: "classic" },
  { text: "Club", value: "club" },
  { text: "Condal", value: "condal" },
  { text: "Dash", value: "dash" },
  { text: "Game Room", value: "game_room" },
  { text: "Glass", value: "glass" },
  { text: "Gothic", value: "gothic" },
  { text: "Graffiti", value: "graffiti" },
  { text: "Icy Sea", value: "icy_sea" },
  { text: "Light", value: "light" },
  { text: "Lolz", value: "lolz" },
  { text: "Luca", value: "luca" },
  { text: "Marble", value: "marble" },
  { text: "Maya", value: "maya" },
  { text: "Metal", value: "metal" },
  { text: "Modern", value: "modern" },
  { text: "Nature", value: "nature" },
  { text: "Neo", value: "neo" },
  { text: "Neo Wood", value: "neo_wood" },
  { text: "Neon", value: "neon" },
  { text: "Newspaper", value: "newspaper" },
  { text: "Ocean", value: "ocean" },
  { text: "Sky", value: "sky" },
  { text: "Space", value: "space" },
  { text: "Tigers", value: "tigers" },
  { text: "Tournament", value: "tournament" },
  { text: "Vintage", value: "vintage" },
  { text: "Wood", value: "wood" },
];
