export const TYPES = [
  { text: "Advanced Pawn", value: "advancedPawn" },
  { text: "Advantage", value: "advantage" },
  { text: "Anastasia Mate", value: "anastasiaMate" },
  { text: "Arabian Mate", value: "arabianMate" },
  { text: "Attacking F2 F7", value: "attackingF2F7" },
  { text: "Attraction", value: "attraction" },
  { text: "Back Rank Mate", value: "backRankMate" },
  { text: "Bishop Endgame", value: "bishopEndgame" },
  { text: "Boden Mate", value: "bodenMate" },
  { text: "Castling", value: "castling" },
  { text: "Capturing Defender", value: "capturingDefender" },
  { text: "Crushing", value: "crushing" },
  { text: "Double Bishop Mate", value: "doubleBishopMate" },
  { text: "Dovetail Mate", value: "dovetailMate" },
  { text: "Equality", value: "equality" },
  { text: "Kingside Attack", value: "kingsideAttack" },
  { text: "Clearance", value: "clearance" },
  { text: "Defensive Move", value: "defensiveMove" },
  { text: "Deflection", value: "deflection" },
  { text: "Discovered Attack", value: "discoveredAttack" },
  { text: "Double Check", value: "doubleCheck" },
  { text: "Endgame", value: "endgame" },
  { text: "En Passant", value: "enPassant" },
  { text: "Exposed King", value: "exposedKing" },
  { text: "Fork", value: "fork" },
  { text: "Hanging Piece", value: "hangingPiece" },
  { text: "Hook Mate", value: "hookMate" },
  { text: "Interference", value: "interference" },
  { text: "Intermezzo", value: "intermezzo" },
  { text: "Kill Box Mate", value: "killBoxMate" },
  { text: "Vukovic Mate", value: "vukovicMate" },
  { text: "Knight Endgame", value: "knightEndgame" },
  { text: "Long", value: "long" },
  { text: "Master", value: "master" },
  { text: "Master vs Master", value: "masterVsMaster" },
  { text: "Mate", value: "mate" },
  { text: "Mate In 1", value: "mateIn1", default: true },
  { text: "Mate In 2", value: "mateIn2" },
  { text: "Mate In 3", value: "mateIn3" },
  { text: "Mate In 4", value: "mateIn4" },
  { text: "Mate In 5", value: "mateIn5" },
  { text: "Middlegame", value: "middlegame" },
  { text: "One Move", value: "oneMove" },
  { text: "Opening", value: "opening" },
  { text: "Pawn Endgame", value: "pawnEndgame" },
  { text: "Pin", value: "pin" },
  { text: "Promotion", value: "promotion" },
  { text: "Queen Endgame", value: "queenEndgame" },
  { text: "Queen Rook Endgame", value: "queenRookEndgame" },
  { text: "Queenside Attack", value: "queensideAttack" },
  { text: "Quiet Move", value: "quietMove" },
  { text: "Rook Endgame", value: "rookEndgame" },
  { text: "Sacrifice", value: "sacrifice" },
  { text: "Short", value: "short" },
  { text: "Skewer", value: "skewer" },
  { text: "Smothered Mate", value: "smotheredMate" },
  { text: "Super GM", value: "superGM" },
  { text: "Trapped Piece", value: "trappedPiece" },
  { text: "Under Promotion", value: "underPromotion" },
  { text: "Very Long", value: "veryLong" },
  { text: "X Ray Attack", value: "xRayAttack" },
  { text: "Zugzwang", value: "zugzwang" },
  { text: "Mix", value: "mix" },
  { text: "Player Games", value: "playerGames" },
];
